import type { Metadata } from "next";

import React from "react";

import "@/src/app/styles/globals.css";
import { Footer } from "@/src/widgets/footer/ui";
import { Header } from "@/src/widgets/header/ui";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Header />
        <main className="desktop:pt-172 pt-90 relative">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
